export const dataMovies = [
  {
    title: "Sonic 1",
    typePelicula: "Pelicula",
    descriptionPelicula: "Sonic intenta atravesar las complejidades de la vida en la Tierra con su nuevo mejor amigo, un humano llamado Tom Wachowski. Deberán unir sus fuerzas para evitar que el malvado Dr. Robotnik capture a Sonic y use sus poderes para dominar el mundo.",
    trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Sonic%201%20La%20Pel%C3%ADcula%20_%20Tr%C3%A1iler%20Oficial.mp4",
    movieVideo: "https://ia800806.us.archive.org/15/items/son-1c-1/Son1c%201.mp4",
    thumbnailUrl: "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/peliculas-images/sonic1-1.jpg",
    genre: ["Aventuras", "Fantástico", "Comedia", "Acción", "Videojuego", "Cine familiar"],
    duration: "1h 39min",
    age: "Familiar",
  },
  {
    title: "Sonic 2",
    typePelicula: "Pelicula",
    descriptionPelicula: "Sonic y su compañero Tails emprenden un viaje alrededor del mundo en busca de una esmeralda que tiene del poder de destruir civilizaciones.",
    trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/Sonic%202%20La%20Pel%C3%ADcula_%20Tr%C3%A1iler%20Oficial.mp4",
    movieVideo: "https://ia803407.us.archive.org/35/items/s-0n-1c-2/S0n1c%202.mp4",
    thumbnailUrl: "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/peliculas-images/sonic2-1.jpg",
    genre: ["Aventuras", "Fantástico", "Comedia", "Acción", "Videojuego", "Cine familiar"],
    duration: "2h 02min",
    age: "Familiar",
  },
  {
    title: "OppenHeimer",
    typePelicula: "Pelicula",
    descriptionPelicula: "Durante la Segunda Guerra Mundial, el teniente general Leslie Groves designa al físico J. Robert Oppenheimer para un grupo de trabajo que está desarrollando el Proyecto Manhattan, cuyo objetivo consiste en fabricar la primera bomba atómica.",
    trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/Sonic%203%20La%20Pel%C3%ADcula%20_%20Tr%C3%A1iler%20Oficial.mp4",
    movieVideo: "https://ia800608.us.archive.org/19/items/opehei-peli-com-lat/Opeheimer-pelicula.mp4",
    thumbnailUrl: "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/peliculas-images/Opheimer-1.jpg",
    genre: ["Suspenso", "Guerra mundial", "Pieza de epoca"],
    duration: "3h 00min",
    age: "18",
  },
];
