export const dataMovies = [
  {
    title: "Flash",
    typePelicula: "Movie",
    descriptionPelicula: "Un joven obtiene la capacidad de moverse a velocidades sobrehumanas y usa sus poderes para salvar el mundo.",
    trailerVideo: "https://youtu.be/hebWYacbdvc?si=iNs1OlXA6j61eCEs",
    movieVideo: "https://youtu.be/hebWYacbdvc?si=iNs1OlXA6j61eCEs",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-1.webp",
    genre: ["Drama", "Family", "Action"],
    duration: "1h 20 min",
    age: "12",
  },
  {
    title: "Los feos",
    typePelicula: "Movie",
    descriptionPelicula: "Un grupo de amigos desafía los estándares de belleza en una sociedad superficial.",
    trailerVideo: "https://youtu.be/1S3CH69dSWg?si=Gv-k5JEcuk6hIguw",
    movieVideo: "https://youtu.be/1S3CH69dSWg?si=Gv-k5JEcuk6hIguw",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-2.webp",
    genre: ["Drama", "Family", "Action"],
    duration: "2h 5 min",
    age: "12",
  },
  {
    title: "Karate Kid",
    typePelicula: "Movie",
    descriptionPelicula: "Un joven aprende artes marciales para defenderse del acoso y descubre el verdadero significado del honor.",
    trailerVideo: "https://youtu.be/r_8Rw16uscg?si=mSTx4uyLKU-xRH4T",
    movieVideo: "https://youtu.be/r_8Rw16uscg?si=mSTx4uyLKU-xRH4T",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-3.webp",
    genre: ["Drama", "Family", "Action"],
    duration: "1h 10 min",
    age: "0",
  },
  {
    title: "Super detective en Hollywood",
    typePelicula: "Movie",
    descriptionPelicula: "Un astuto policía de Detroit viaja a Beverly Hills para resolver el asesinato de su mejor amigo.",
    trailerVideo: "https://youtu.be/1UV-lUZIyQk?si=ZowIke7IN8QaJIyf",
    movieVideo: "https://youtu.be/1UV-lUZIyQk?si=ZowIke7IN8QaJIyf",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-4.webp",
    genre: ["Drama", "Family", "Action"],
    duration: "2h 10 min",
    age: "0",
  },
  {
    title: "Fracture",
    typePelicula: "Movie",
    descriptionPelicula: "Un abogado enfrenta el caso más complicado de su carrera cuando un hombre confiesa haber intentado matar a su esposa.",
    trailerVideo: "https://youtu.be/UG1Lxnn8Qa8?si=IbWiaqtsDHXP2Z_L",
    movieVideo: "https://youtu.be/UG1Lxnn8Qa8?si=IbWiaqtsDHXP2Z_L",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-5.webp",
    genre: ["Drama", "Family", "Action"],
    duration: "1h 50 min",
    age: "18",
  },
  {
    title: "Spiderman",
    typePelicula: "Movie",
    descriptionPelicula: "Un joven adquiere poderes arácnidos y lucha contra el crimen mientras enfrenta sus propios problemas personales.",
    trailerVideo: "https://youtu.be/rk-dF1lIbIg?si=h9XMfVNyWWhHENk7",
    movieVideo: "https://youtu.be/rk-dF1lIbIg?si=h9XMfVNyWWhHENk7",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-6.webp",
    genre: ["Action", "Family", "Marvel"],
    duration: "2h 30 min",
    age: "0",
  },
  {
    title: "Al filo del mañana",
    typePelicula: "Movie",
    descriptionPelicula: "Un soldado atrapado en un bucle temporal debe revivir el mismo combate una y otra vez para derrotar a una raza alienígena.",
    trailerVideo: "https://youtu.be/Qd0_qYIhMZA?si=uLfjQRBuRG88bZC3",
    movieVideo: "https://youtu.be/Qd0_qYIhMZA?si=uLfjQRBuRG88bZC3",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-7.webp",
    genre: ["Action", "Family", "Marvel"],
    duration: "1h 35 min",
    age: "16",
  },
  {
    title: "Top Gun",
    typePelicula: "Movie",
    descriptionPelicula: "Un talentoso piloto de combate lucha por demostrar su valía en la academia de aviación más exigente del mundo.",
    trailerVideo: "https://youtu.be/zmFdhZ6gyUM?si=RZGSU3cXyuSOYdTJ",
    movieVideo: "https://youtu.be/zmFdhZ6gyUM?si=RZGSU3cXyuSOYdTJ",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-8.webp",
    genre: ["Action", "Family", "Marvel"],
    duration: "2h 35 min",
    age: "18",
  },
  {
    title: "Jack Reacher",
    typePelicula: "Movie",
    descriptionPelicula: "Un exinvestigador militar investiga un crimen que lo lleva a descubrir una conspiración mucho más grande.",
    trailerVideo: "https://youtu.be/UwLsJ54wa6w?si=mIT63FFSCkUaOpLj",
    movieVideo: "https://youtu.be/UwLsJ54wa6w?si=mIT63FFSCkUaOpLj",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-9.webp",
    genre: ["Action", "Family", "Marvel"],
    duration: "1h 50 min",
    age: "16",
  },
  {
    title: "Sonic",
    typePelicula: "Movie",
    descriptionPelicula: "Un veloz erizo azul llega a la Tierra y se une a un humano para salvar el mundo del malvado Dr. Robotnik.",
    trailerVideo: "https://youtu.be/XPqAai3WBag?si=v9YFDIK0EcHBnS4I",
    movieVideo: "https://youtu.be/XPqAai3WBag?si=v9YFDIK0EcHBnS4I",
    thumbnailUrl: "https://raw.githubusercontent.com/ratasi/images-netflix-clone/refs/heads/main/movies/movie-10.webp",
    genre: ["Action", "Family", "Marvel"],
    duration: "2h 05 min",
    age: "18",
  },
];
