export const dataAnime = [
    {
      title: "Ranma ½ - Remake",
      description: "Ranma ½ es una serie de comedia y acción que cuenta la historia de Ranma, un joven que se ve afectado por una maldición que lo convierte en una chica cuando se moja con agua fría.",
      type: "serie",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Ranma12-t1.jpg",
      genre: ["Acción", "Comedia", "romántica", "Aventura", "Ecchi"],
      age: "13",
      duration: "1 Temporada",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Ranma%20remake%20-%20Trailer%20oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "La llegada de Ranma",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/is5agiukdd9gum4e71cvp/01-La-llegada-de-Ranma.mp4?rlkey=j7xy5bo5y0hekbn6gefko7bve&st=t4oynl24&dl=0",
            },
            {
              number: 2,
              title: "Odio a los hombres",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/ojp75hdh7fh5fw2f9rhkf/02-Odio-a-los-hombres.mp4?rlkey=udi8tmjxwib7hcnufmcou80ro&st=i5eoir3a&dl=0",
            },
            {
              number: 3,
              title: "Porque le gusta alguien",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/yr7gzicak3crk0d88fog9/03-Porque-le-gusta-alguien.mp4?rlkey=1gzjht6n8mvgur96bbprjip1o&st=6svz8roj&dl=0",
            },
            {
              number: 4,
              title: "El hombre que perseguia a Ranma",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/iwlnr533nbjtcsdz1sehx/04-El-hombre-que-persegu-a-a-Ranma.mp4?rlkey=p67c5kw55idb1gea15g1eetcs&st=hf4r3l1q&dl=0",
            },
            {
              number: 5,
              title: "Eres odiosa",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/h06ys155piz2kfebi7fly/05-Eres-odiosa.mp4?rlkey=lwe505cpm7x1cwtnw13l28twh&st=nin6j129&dl=0",
            },
            {
              number: 6,
              title: "Kodachi la rosa negra",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/ya63eisppb1h5yprjv87d/06-Kodachi-de-la-rosa-negra.mp4?rlkey=4uki5zliysp5j3qawig354cbf&st=tur9elmj&dl=0",
            },
            {
              number: 7,
              title: "Una disputada lucha gimnástica",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/9i2aa92pntoa4sxr53eb3/07-Una-disputada-lucha-gimn-stica.mp4?rlkey=dzbn41ibm9wlnwx9rv7ykfa52&st=uptjvglr&dl=0",
            },
            {
              number: 8,
              title: "Mi querido charlotte",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/5elg454xguymbpokvaok9/08-Mi-querido-Charlotte.mp4?rlkey=9n2p8kz50dvf02sus4e4wxcv6&st=0ggs49uk&dl=0",
            },
            {
              number: 9,
              title: "Jamas te soltaré",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/dkszcor6l0tanyj77b35q/09-Jam-s-te-soltar.mp4?rlkey=mmeby3rpdtm5vc1spaxq8ny4t&st=0r4ngb4v&dl=0",
            },
            {
              number: 10,
              title: "El beso de la muerte",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/zjg27x14rhms8fc1t6alm/10-El-beso-de-la-muerte.mp4?rlkey=ybjsv5rz67i58ipp90t9w60sv&st=bzjc9jbd&dl=0",
            },
            {
              number: 11,
              title: "Wo ai ni",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/munx0i1gt639twk8zz48m/11-Wo-ai-ni.mp4?rlkey=7bqho5j64z9npt6kzbcrze5ge&st=tgco9nrx&dl=0",
            },
            {
              number: 12,
              title: "El champú amnésico",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/tsmcuy25dps6n2x3adyuj/12-El-champ-amn-sico.mp4?rlkey=pmfodscbrcbzgg0d27alr9c73&st=m5e7bch6&dl=0",
            },
          ],
        },
      ],
    },
    {
      title: "Sakamoto Days",
      description: "Taro Sakamoto era conocido como el sicario más fuerte, temido por los villanos y un ejemplo a seguir para el resto de sicarios. Sin embargo, un día... ¡Se enamoró! Se retiró, se casó, se convirtió en padre y... ¡Engordó! Ahora es un hombre regordete que lleva una tienda. Sin embargo, ¡su verdadera identidad es la de un asesino legendario! Como padre de una niña, deberá proteger a su familia y su vida cotidiana de los inminentes peligros.",
      type:"Anime",
      thumbnailUrl:
      "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Sakamoto_Days-1.jpg",
      genre: ["Acción", "recuentos de la vida", "comedia"],
      age: "13",
      duration: "1 Temporada - En emison",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Sakamoto%20Days%20Trailer%20Oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.El asesino legendario",
              duration: "25 min",
              videoUrl: "https://www.dropbox.com/scl/fi/5w7v7q3e66ey3fjv1zxq4/01-SKMTODays.mp4?rlkey=pukaw7sm5wvicxvrze52vjue8&st=m3holvzj&dl=0",
            },
            {
              number: 2,
              title: "02.La batalla contra Son Hee y Bacho",
              duration: "25 min",
              videoUrl: "https://www.dropbox.com/scl/fi/dirjb8prd0uz2ktow7c22/02-SKMTODays.mp4?rlkey=s6yw5ta2jxnwnypn6bkb8dw44&st=a8y2lzye&dl=0",
            },
            {
              number: 3,
              title: "03.Bienvenido a sugar park",
              duration: "25 min",
              videoUrl: "https://www.dropbox.com/scl/fi/mnyr989th7x7z12lwylxl/03-SAKMTODays.mp4?rlkey=uj2hksbr8ldt3ocgdb4xj8u5r&st=x02bf45x&dl=0",
            },
            {
              number: 4,
              title: "04.Hard Boiled",
              duration: "24 min",
              videoUrl: "https://www.dropbox.com/scl/fi/k70ddi8cfvtgnnc46kw42/04-SAKMTODays.mp4?rlkey=3s6la4hhyb9bphgxg28tg2bzj&st=mz41vac5&dl=0",
            },
          ],
        },
      ],
    },
    {
      title: "Alya Sometimes Hides Her Feelings in Russian",
      description: "Alya es una estudiante recién transferida que disfruta de tener buenas calificaciones y mucha popularidad en su nueva preparatoria, aunque lo habitual es que luzca muy fría. No suele hablar nunca con un compañero de clase muy estudioso llamado Kuza Masachika, y cuando lo hace, es para decirle algún halago en ruso. Lo que ella no sabe es que Kuze entiende el ruso, aunque hace ver que no. ¡Comprobemos hasta dónde llega esta curiosa historia de amor!",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Alya-1.jpg",
      genre: ["Animación", "Vida escolar", "Comedia", "Ecchi"],
      age: "15",
      duration: "1 Temporada",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Alya%20Sometimes%20Hides%20Her%20Feelings%20in%20Russian%20-%20Official%20Trailer.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Alya esconde sus sentimientos en ruso",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Vaya amigos de la infancia",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.Así se conocieron",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.Un flujo de emociones",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.Gente distinta, trasfondos comunes",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.Un beso de tipo indirecto",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Llega una tormenta",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.El congreso escolar",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.Comedia romántica con posibilidad de hipnosis",
              duration: "24min",
              videoUrl: "https://ia600808.us.archive.org/23/items/ep-9_20250204/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Fiesta de cumpleaños muy atrasada",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/23/items/ep-9_20250204/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.Una previa inesperada",
              duration: "24min",
              videoUrl: "https://ia600808.us.archive.org/23/items/ep-9_20250204/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.Cabeza arriba y mira al frente",
              duration: "25min",
              videoUrl: "https://ia600808.us.archive.org/23/items/ep-9_20250204/Ep12.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Kaiju No.8",
      description: "La historia la protagoniza Kafka Hibino, un hombre de 32 años que quiere unirse a la Fuerza de Defensa y cumplir la promesa que le hizo a una amiga de la infancia, Mina Ashiro. En su trabajo como limpiador de restos de Kaiju forja amistad con un nuevo compañero, Reno Ichikawa, cuya determinación de unirse a la Fuerza de Defensa inspira a Kafka a cumplir su promesa de la infancia de unirse a Mina para proteger a la humanidad. Cuando un pequeño Kaiju se introduce en el interior de Kafka, éste adquiere una fuerza sobrehumana y poderes que le permiten luchar contra los Kaiju. Ahora se esfuerza por ganarse la confianza de sus compañeros humanos, derrotar a unos Kaiju cada vez más poderosos y proteger el mundo.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/kaiju8-1.jpg",
      genre: ["Acción", "horror", "sobrenatural", "ciencia ficción", "fantástica", "aventura​"],
      age: "13",
      duration: "12 Episodios",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Kaiju%20No.%208%20_%20TR%C3%81ILER%20OFICIAL.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.El hombre que se conviritó en kaiju",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/01.El%20hombre%20que%20se%20convirti%C3%B3%20en%20kaiju.mp4",
            },
            {
              number: 1,
              title: "02.El kaiju que elimina a otros kaiju",
              duration: "23min",
              videoUrl: "https://ia600807.us.archive.org/9/items/07.-kaiju-no.-8/02.El%20kaiju%20que%20elimina%20a%20otros%20kaiju.mp4",
            },
            {
              number: 1,
              title: "03.Partido de revancha",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/03.Partido%20de%20revancha.mp4",
            },
            {
              number: 1,
              title: "04.Onda de generación 9.8",
              duration: "23min",
              videoUrl: "https://ia600807.us.archive.org/9/items/07.-kaiju-no.-8/04.Onda%20de%20generaci%C3%B3n%209.8.mp4",
            },
            {
              number: 1,
              title: "05.¡Alistamiento!",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/05.%C2%A1Alistamiento%21.mp4",
            },
            {
              number: 1,
              title: "06.Operación de caza al amanacer en Sagamihara",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/06.Operaci%C3%B3n%20de%20caza%20al%20amanecer%20en%20Sagamihara.mp4",
            },
            {
              number: 1,
              title: "07.Kaiju número 9",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/07.Kaiju%20No.%209.mp4",
            },
            {
              number: 1,
              title: "08.Bienvenido a las fuezas de defensa",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/08.Bienvenido%20a%20las%20fuerzas%20de%20defensa.mp4",
            },
            {
              number: 1,
              title: "09.Ataque a la base Tachikawa",
              duration: "23min",
              videoUrl: "https://ia600807.us.archive.org/9/items/07.-kaiju-no.-8/09.Ataque%20a%20la%20base%20de%20Tachikawa.mp4",
            },
            {
              number: 1,
              title: "10.Expuesto",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/10.Expuesto.mp4",
            },
            {
              number: 1,
              title: "11.El kaiju número 8 es capturado",
              duration: "23min",
              videoUrl: "https://ia800807.us.archive.org/9/items/07.-kaiju-no.-8/11.El%20kaiju%20No.8%20es%20capturado.mp4",
            },
            {
              number: 1,
              title: "12.Kafka Hibino",
              duration: "23min",
              videoUrl: "https://ia600807.us.archive.org/9/items/07.-kaiju-no.-8/12.Kafka%20Hibino.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Uzaki-chan Wants to Hang Out!",
      description: "Shinichi Sakurai va a la universidad, no le molesta ser un solitario introvertido y no le importa lo que piensen los demás. La voluptuosa Hana Uzaki de segundo año no puede semejante cosa. Alegre como ella sola, se propuso hacer que él sea más social. A él le gusta su compañía, y dejó que sea su amiga. ¿Es posible pasarla bien con los demás tanto como estando solo?",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Uzachan-1.jpg",
      genre: ["Comedia"],
      age: "15",
      duration: "2 Temporadas",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Uzaki-Chan%20Wants%20to%20Hang%20Out_%20Temporada%202%20_%20TR%C3%81ILER%20OFICIAL.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.¡Uzaki-chan quiere divertirse!",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/01.%C2%A1Uzaki-chan%20quiere%20divertirse%21.mp4",
            },
            {
              number: 1,
              title: "02.¡El dueño quiere curiosear!",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/02.%C2%A1El%20due%C3%B1o%20quiere%20curiosear%21.mp4",
            },
            {
              number: 1,
              title: "03.Los Asai quieren cuidarnos",
              duration: "23min",
              videoUrl: "https://ia800702.us.archive.org/25/items/UzakichanAsobatai/03.Los%20Asai%20quieren%20cuidarnos.mp4",
            },
            {
              number: 1,
              title: "04.Estemos juntos en las vacaciones",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/04.Estemos%20juntos%20en%20las%20vacaciones.mp4",
            },
            {
              number: 1,
              title: "05.Quiero entrometerme en los asuntos de mi amigo",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/05.Quiero%20entrometerme%20en%20los%20asuntos%20de%20mi%20amigo.mp4",
            },
            {
              number: 1,
              title: "06.Probaré mi valor en la playa",
              duration: "23min",
              videoUrl: "https://ia800702.us.archive.org/25/items/UzakichanAsobatai/06.Probare%20mi%20valor%20en%20la%20playa.mp4",
            },
            {
              number: 1,
              title: "07.¡Quiero ir a un café!",
              duration: "23min",
              videoUrl: "https://ia800702.us.archive.org/25/items/UzakichanAsobatai/07.%C2%A1Quiero%20ir%20a%20un%20caf%C3%A9%21.mp4",
            },
            {
              number: 1,
              title: "08.Disfrutemos juntos de los fuegos artificiales",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/08.Disfrutemos%20juntos%20de%20los%20fuegos%20artificiales.mp4",
            },
            {
              number: 1,
              title: "09.¿Uzaki busca emoción?",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/09.Uzaki%20busca%20emoci%C3%B3n.mp4",
            },
            {
              number: 1,
              title: "10.¡Quiero que vayamos a Tottori!",
              duration: "23min",
              videoUrl: "https://ia800702.us.archive.org/25/items/UzakichanAsobatai/10.%C2%A1Quiero%20que%20vayamos%20a%20Tottori%21.mp4",
            },
            {
              number: 1,
              title: "11.¿Sakurai también quiere divertirse?",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/11.Sakurai%20tambien%20quiere%20divertirse.mp4",
            },
            {
              number: 1,
              title: "12.¡Uzaki-chan quiere más!",
              duration: "23min",
              videoUrl: "https://ia600702.us.archive.org/25/items/UzakichanAsobatai/12.%C2%A1Uzaki-chan%20quiere%20mas%21.mp4",
            },
          ],
        },
        {
          number: 2,
          episodes: [
            {
              number: 2,
              title: "01.Cómo no, ¡Uzaki quiere divertirse!",
              duration: "23 min",
              videoUrl: "https://ia600702.us.archive.org/5/items/AsobataiUzakichan/01.Como%20no%20%C2%A1Uzaki%20quiere%20divertirse%21.mp4",
            },
            {
              number: 2,
              title: "02.Después de divertirse,¡quiere hacer udon!",
              duration: "23 min",
              videoUrl: "https://ia600702.us.archive.org/5/items/AsobataiUzakichan/02.Despues%20de%20divertirse%20%C2%A1quiere%20hacer%20udon%21.mp4",
            },
            {
              number: 2,
              title: "03.¿Uzaki quiere ir al festival escolar?",
              duration: "23 min",
              videoUrl: "https://ia600702.us.archive.org/5/items/AsobataiUzakichan/03.Uzaki%20quiere%20ir%20al%20festival%20escolar.mp4",
            },
            {
              number: 2,
              title: "04.¡Uzaki quiere ser superior!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/04.%C2%A1Uzaki%20quiere%20ser%20superior%21.mp4",
            },
            {
              number: 2,
              title: "05.¡Uzaki quiere capturarlos a todos!",
              duration: "23 min",
              videoUrl: "https://ia600702.us.archive.org/5/items/AsobataiUzakichan/05.%C2%A1Uzaki%20quiere%20capturarlos%20a%20todos%21.mp4",
            },
            {
              number: 2,
              title: "06.¡Uzaki se muere por celebrar!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/06.%C2%A1Uzaki%20se%20muere%20por%20celebrar%21.mp4",
            },
            {
              number: 2,
              title: "07.¡Uzaki quiere hacer que se le declare!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/07.%C2%A1Uzaki%20quiere%20hacer%20que%20se%20le%20declare%21.mp4",
            },
            {
              number: 2,
              title: "08.¡Yanagi y Kiri quieren divertirse!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/08.%C2%A1Yanagi%20y%20Kiri%20quieren%20divertirse%21.mp4",
            },
            {
              number: 2,
              title: "09.¡Fujio Uzaki quiere divertirse en familia!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/09.%C2%A1Fujio%20Uzaki%20quiere%20divertirse%20en%20familia%21.mp4",
            },
            {
              number: 2,
              title: "10.¡Quiero que se emocione antes de navidad!",
              duration: "23 min",
              videoUrl: "https://ia600702.us.archive.org/5/items/AsobataiUzakichan/10.%C2%A1Quiero%20que%20se%20emocione%20antes%20de%20navidad%21.mp4",
            },
            {
              number: 2,
              title: "11.¡Creo que ya quiero formalizar!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/11.%C2%A1Creo%20que%20ya%20quiero%20formalizar%21.mp4",
            },
            {
              number: 2,
              title: "12.¡Quiero divertirme en nochebuena!",
              duration: "23 min",
              videoUrl: "https://ia800702.us.archive.org/5/items/AsobataiUzakichan/12.%C2%A1Quiero%20divertirme%20en%20nochebuena%21.mp4",
            },
            {
              number: 2,
              title: "13.¡Quiero divertirme contigo el próximo año!",
              duration: "23 min",
              videoUrl: "https://ia600702.us.archive.org/5/items/AsobataiUzakichan/13.%C2%A1Quiero%20divertirme%20contigo%20el%20proximo%20a%C3%B1o%21.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "More than a Married Couple, but Not Lovers",
      description: "¿Alguna vez pensaste que en la enseñanza deberían incluirse cosas más útiles para el día a día? Pues es lo que ocurre aquí, donde se empareja a los estudiantes para que practiquen cómo será la vida de casados durante un tiempo, ¡y eso incluye vivir juntos! ¿Qué puede salir mal cuando la suerte empareja a una gal con un estudiante algo retraído que prefiere jugar a videojuegos en lugar de relacionarse? ¡Lo peor es que tendrán que esforzarse si quieren aprobar!",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/fuufu-1.jpg",
      genre: ["Animación","Drama","Romance","Comedia"],
      age: "14",
      duration: "12 Episodios",
      trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/More%20Than%20a%20Married%20Couple_%20But%20Not%20Lovers%20-%20TRAILER%20OFICIAL.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Prácticas de matrimonio",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/01.Vivir%20en%20el%20mismo%20lugar%2C%20pero%20no%20vivir%20juntos.mp4",
            },
            {
              number: 1,
              title: "02.Imaginario, no real",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/02.Imaginario%2C%20no%20real.mp4",
            },
            {
              number: 1,
              title: "03.Separados, no reavivados",
              duration: "24min",
              videoUrl: "https://ia600808.us.archive.org/15/items/FuufuIjou-koibitomiman/03.Separados%2C%20no%20reavivados.mp4",
            },
            {
              number: 1,
              title: "04.Héroe, pero no protagonista",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/04.Heroe%2C%20pero%20no%20protagonista.mp4",
            },
            {
              number: 1,
              title: "05.Más que una emorragia nasal, menos que un beso",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/05.Mas%20que%20una%20hemorragia%20nasal%2C%20menos%20que%20un%20beso.mp4",
            },
            {
              number: 1,
              title: "06.Un chico virge, ninguna chica virgen",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/06.Un%20chico%20virgen%2C%20ninguna%20chica%20virgen.mp4",
            },
            {
              number: 1,
              title: "07.Fuegos artificiales sin abrazo",
              duration: "24min",
              videoUrl: "https://ia600808.us.archive.org/15/items/FuufuIjou-koibitomiman/07.Furgos%20artificiales%20sin%20abrazo.mp4",
            },
            {
              number: 1,
              title: "08.Una súplica sin consuelo",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/08.Una%20suplica%20sin%20consuelo.mp4",
            },
            {
              number: 1,
              title: "09.Más que un amigo de la infancia, sin llegar a amor verdadero",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/09.Mas%20que%20un%20amigo%20de%20la%20infancia%2C%20sin%20llegar%20a%20amor%20verdadero.mp4",
            },
            {
              number: 1,
              title: "10.El ahora ya ha pasado... pero aún no",
              duration: "24min",
              videoUrl: "https://ia600808.us.archive.org/15/items/FuufuIjou-koibitomiman/10.El%20ahora%20ya%20ha%20pasado...%20pero%20aun%20no.mp4",
            },
            {
              number: 1,
              title: "11.Más que una declaración, sin llegar a mal de amores",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/11.Mas%20que%20una%20declaraci%C3%B3n%2C%20sin%20llegar%20a%20mal%20de%20amores.mp4",
            },
            {
              number: 1,
              title: "12.Nada menos que amor",
              duration: "24min",
              videoUrl: "https://ia800808.us.archive.org/15/items/FuufuIjou-koibitomiman/12.Nada%20menos%20que%20amor.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Assesination classroom",
      description: "Olvídense de los deberes y los exámenes sorpresa. Los estudiantes de la clase 3E tienen una tarea mucho más importante: ¡matar a su maestro antes de fin de año! Un sensei con tentáculos que se mueve a Mach 20 está dispuesto a conquistar el aula después de destruir el setenta por ciento de la luna. Además de leer, escribir y aritmética, el monstruo asesino detrás del atril les enseñará a sus estudiantes todo lo que sabe sobre el juego del asesinato. Si algún castor ansioso demuestra ser un estudiante rápido en el asesinato, salvará a la Tierra de la extinción y obtendrá una gran recompensa.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/AsseClassroom-1.jpg",
      genre: ["Acción","Ciencia ficción", "Comedia dramática"],
      age: "14",
      duration: "2 Temporadas",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Assassination%20Classroom%20-%20Official%20Trailer.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Hora de asesinar",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/01.Hora%20de%20asesinar.mp4",
            },
            {
              number: 1,
              title: "02.Hora de béisbol",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/02.Hora%20de%20b%C3%A9isbol.mp4",
            },
            {
              number: 1,
              title: "03.Hora de Karma",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/03.Hora%20de%20karma.mp4",
            },
            {
              number: 1,
              title: "04.Hora de adultos",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/04.Hora%20de%20los%20adultos.mp4",
            },
            {
              number: 1,
              title: "05.Hora de la asamblea",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/05.Hora%20de%20la%20asamblea.mp4",
            },
            {
              number: 1,
              title: "06.Hora de los exámenes",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/06.Hora%20de%20los%20ex%C3%A1menes.mp4",
            },
            {
              number: 1,
              title: "07.Hora de la excursión pt.1",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/07.Hora%20de%20la%20excursi%C3%B3n%20pt.1.mp4",
            },
            {
              number: 1,
              title: "08.Hora de la excursión Pt.2",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/08.Hora%20de%20la%20excursi%C3%B3n%20pt.2.mp4",
            },
            {
              number: 1,
              title: "09.Hora del estudiante de intercambio",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/09.Hora%20del%20estudiante%20de%20intercambio%20pt.1.mp4",
            },
            {
              number: 1,
              title: "10.Hora de L y R",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/10.Hora%20de%20L%20y%20R.mp4",
            },
            {
              number: 1,
              title: "11.Hora del estudiante de intercambio Pt.2",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/11.Hora%20del%20estudiante%20de%20intercambio%20pt.2.mp4",
            },
            {
              number: 1,
              title: "12.Hora del torneo",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/12.Hora%20del%20torneo.mp4",
            },
            {
              number: 1,
              title: "13.Hora del talento",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/13.Hora%20del%20talento.mp4",
            },
            {
              number: 1,
              title: "14.Hora de la visión",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/14.Hora%20de%20la%20visi%C3%B3n.mp4",
            },
            {
              number: 1,
              title: "15.Hora de los exámenes finales",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/15.Hora%20de%20los%20examenes%20finales.mp4",
            },
            {
              number: 1,
              title: "16.Fin de las clases, primer semestre",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/16.Fin%20de%20las%20clases%20%28primer%20trimestre%29.mp4",
            },
            {
              number: 1,
              title: "17.Hora de la isla",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/17.Hora%20de%20la%20isla.mp4",
            },
            {
              number: 1,
              title: "18.Hora de la acción",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/18.Hora%20de%20la%20acci%C3%B3n.mp4",
            },
            {
              number: 1,
              title: "19.Hora del pandemónium",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/19.Hora%20del%20pandemonium.mp4",
            },
            {
              number: 1,
              title: "20.Hora de karma Pt.2",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/20.Hora%20de%20karma%20pt.2.mp4",
            },
            {
              number: 1,
              title: "21.Hora de XX",
              duration: "23min",
              videoUrl: "https://ia800107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/21.Hora%20de%20XX.mp4",
            },
            {
              number: 1,
              title: "22.Hora de Nagisa",
              duration: "23min",
              videoUrl: "https://ia600107.us.archive.org/25/items/Ass3sinat1onCl4ssr00mT1/22.Hora%20de%20Nagisa.mp4",
            },
          ],
        },
        {
          number: 2,
          episodes: [
            {
              number: 2,
              title: "S2 01.Hora del festival de verano",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/23.Hora%20del%20festival%20de%20verano.ia.mp4",
            },
            {
              number: 2,
              title: "S2 02.Hora de Kaede",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/24.Hora%20de%20Kaede.mp4",
            },
            {
              number: 2,
              title: "S2 03.Hora de Itona Horibe",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/25.Hora%20de%20Itona%20Horibe.mp4",
            },
            {
              number: 2,
              title: "S2 04.Hora de hilar",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/26.Hora%20de%20hilar.mp4",
            },
            {
              number: 2,
              title: "S2 05.Hora del lider",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/27.Hora%20de%20lider.mp4",
            },
            {
              number: 2,
              title: "S2 06.Hora del antes y el después",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/28.Hora%20de%20before%20after.mp4",
            },
            {
              number: 2,
              title: "S2 07.Hora del shinigami pt.1",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/29.Hora%20de%20dios%20de%20la%20muerte%20pt.1.mp4",
            },
            {
              number: 2,
              title: "S2 08.Hora del shinigami Pt.2",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/30.Hora%20de%20dios%20de%20la%20muerte%20pt.2.mp4",
            },
            {
              number: 2,
              title: "S2 09.Hora de la segunda ronda",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/31.Hora%20de%20segunda%20ronda.mp4",
            },
            {
              number: 2,
              title: "S2 10.Hora del festival escolar",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/32.Hora%20de%20festival%20escolar.mp4",
            },
            {
              number: 2,
              title: "S2 11.Hora del fin del segundo semestre",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/33.Hora%20de%20finales%20%28segunda%20hora%29.mp4",
            },
            {
              number: 2,
              title: "S2 12.Hora de pensar fuera de la caja",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/34.Hora%20de%20pensar%20fuera%20de%20la%20caja.mp4",
            },
            {
              number: 2,
              title: "S2 13.Hora de dejar vivir",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/35.Hora%20de%20permitir%20vivir.mp4",
            },
            {
              number: 2,
              title: "S2 14.Hora de la identidad secreta",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/36.Hora%20de%20identidad%20secreta.mp4",
            },
            {
              number: 2,
              title: "S2 15.Hora de la confesión",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/37.Hora%20de%20confesi%C3%B3n.mp4",
            },
            {
              number: 2,
              title: "S2 16.Hora del pasado",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/38.Hora%20de%20pasado.mp4",
            },
            {
              number: 2,
              title: "S2 17.Hora de la discordia",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/39.Hora%20de%20discordia.mp4",
            },
            {
              number: 2,
              title: "S2 18.Hora de los resultados",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/40.Hora%20de%20resultado.mp4",
            },
            {
              number: 2,
              title: "S2 19.Hora del espacio",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/41.Hora%20de%20espacio%20exterior.mp4",
            },
            {
              number: 2,
              title: "S2 20.Hora de san valentín",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/42.Hora%20de%20san%20Valent%C3%ADn.mp4",
            },
            {
              number: 2,
              title: "S2 21.Hora de la verdad",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/43.Hora%20de%20confianza.mp4",
            },
            {
              number: 2,
              title: "S2 22.Hora del cumpleaños",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/44.Hora%20de%20feliz%20cumplea%C3%B1os.mp4",
            },
            {
              number: 2,
              title: "S2 23.Hora del jefe final",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/45.Hora%20de%20jefe%20final.mp4",
            },
            {
              number: 2,
              title: "S2 24.Hora de graduación",
              duration: "23min",
              videoUrl: "https://ia800809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/46.Hora%20de%20graduaci%C3%B3n.mp4",
            },
            {
              number: 2,
              title: "S2 25.Hora del futuro",
              duration: "23min",
              videoUrl: "https://ia600809.us.archive.org/13/items/Ass3s1n4ti0nCl4ssr00mT2/47.Hora%20de%20futuro.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Your Name",
      description: "Mitsuha y Taki son dos completos desconocidos que viven vidas completamente diferentes. Pero cuando Mitsuha pide el deseo de dejar su pueblo de montaña para ir a la bulliciosa ciudad de Tokio, ambos se conectan de una manera extraña. Ella sueña que es un chico que vive en Tokio, mientras que Taki sueña que es una chica de un pueblo rural que nunca ha visitado. ¿Qué significa su nueva conexión? ¿Y cómo los unirá? Descúbrelo en la última película del aclamado autor Makoto Shinkai.",
      type:"Pelicula, Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/yourname-1.jpg",
      genre: ["Animación", "Cine romántico","Fantasia","Melodrama","Drama", "Sobrenatural"],
      age: "Todos",
      duration: "1h 47min",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Your%20Name%20-%20Oficial%20Trailer.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "Your Name",
              duration: "1h 46min",
              videoUrl: "https://ia804507.us.archive.org/28/items/your-name-pelicula/Your%20name%20-%20Pelicula.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Horimiya",
      description: "Cuando la popular Hori y el sombrío Miyamura se conocen, revelan el lado oculto de sí mismos. ¿Podría ser esto el comienzo de algo nuevo?",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Horimiya-1.jpg",
      genre: ["Romance", "Drama"],
      age: "14",
      duration: "2 Temporada",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Horimiya_%20The%20Missing%20Pieces%20_%20TR%C3%81ILER%20OFICIAL.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Una pequeña casualidad",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Tienes más de una cara",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.Por eso está bien",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.Todos aman a alguien",
              duration: "23min",
              videoUrl: "https://ia800104.us.archive.org/26/items/HorimiyaT1/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.No puedo decirlo en voz alta",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.Este verano será muy caliente",
              duration: "23min",
              videoUrl: "https://ia800104.us.archive.org/26/items/HorimiyaT1/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Tu estás aqui, yo estoy aqui",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.La verdad revela el engaño",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.Es difícil, pero no imposible",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Hasta que se derrita la nieve",
              duration: "23min",
              videoUrl: "https://ia800104.us.archive.org/26/items/HorimiyaT1/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.Puede parecer odio",
              duration: "23min",
              videoUrl: "https://ia800104.us.archive.org/26/items/HorimiyaT1/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.Hasta ahora y para siempre",
              duration: "23min",
              videoUrl: "https://ia600104.us.archive.org/26/items/HorimiyaT1/Ep12.mp4",
            },
            {
              number: 1,
              title: "13.Te regalaría el cielo",
              duration: "23min",
              videoUrl: "https://ia800104.us.archive.org/26/items/HorimiyaT1/Ep13.mp4",
            },
          ],
        },
        {
          number: 2,
          episodes: [
            {
              number: 2,
              title: "S2 01.Viaje escolar",
              duration: "23min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep1.mp4",
            },
            {
              number: 2,
              title: "S2 02.Clase de cocina",
              duration: "23min",
              videoUrl: "https://ia904502.us.archive.org/0/items/HorimiypiecesT2/Ep2.mp4",
            },
            {
              number: 2,
              title: "S2 03.Festival deportivo",
              duration: "23min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep3.mp4",
            },
            {
              number: 2,
              title: "S2 04.Kotatsu Hori",
              duration: "23min",
              videoUrl: "https://ia904502.us.archive.org/0/items/HorimiypiecesT2/Ep4.mp4",
            },
            {
              number: 2,
              title: "S2 05.lura",
              duration: "23min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep5.mp4",
            },
            {
              number: 2,
              title: "S2 06.Pijamada",
              duration: "23min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep6.mp4",
            },
            {
              number: 2,
              title: "S2 07.Amigos",
              duration: "23min",
              videoUrl: "https://ia904502.us.archive.org/0/items/HorimiypiecesT2/Ep7.mp4",
            },
            {
              number: 2,
              title: "S2 08.Yanagi",
              duration: "23min",
              videoUrl: "https://ia904502.us.archive.org/0/items/HorimiypiecesT2/Ep8.mp4",
            },
            {
              number: 2,
              title: "S2 09.Profesor",
              duration: "23min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep9.mp4",
            },
            {
              number: 2,
              title: "S2 10.Celos",
              duration: "23min",
              videoUrl: "https://ia904502.us.archive.org/0/items/HorimiypiecesT2/Ep10.mp4",
            },
            {
              number: 2,
              title: "S2 11.Chocolates",
              duration: "23min",
              videoUrl: "https://ia904502.us.archive.org/0/items/HorimiypiecesT2/Ep11.mp4",
            },
            {
              number: 2,
              title: "S2 12.La familia Hori",
              duration: "23min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep12.mp4",
            },
            {
              number: 2,
              title: "S2 13.Graduación",
              duration: "26min",
              videoUrl: "https://ia804502.us.archive.org/0/items/HorimiypiecesT2/Ep13.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Terminator Zero",
      description: "Una guerrera de un futuro posapocalíptico viaja a 1997 para proteger a un científico abocado a la inteligencia artificial, que huye de un cíborg insensible e indestructible.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/terZero-1.jpg",
      genre: ["Ciencia ficción","Acción"],
      age: "14",
      duration: "8 Episodios",
      trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/Terminator%20Zero%20_%20Tr%C3%A1iler%20oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Episodio 1",
              duration: "28min",
              videoUrl: "https://ia804600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/01.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "02.Episodio 2",
              duration: "29min",
              videoUrl: "https://ia904600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/02.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "03.Episodio 3",
              duration: "30min",
              videoUrl: "https://ia804600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/03.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "04.Episodio 4",
              duration: "27min",
              videoUrl: "https://ia804600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/04.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "05.Episodio 5",
              duration: "30min",
              videoUrl: "https://ia904600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/05.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "06.Episodio 6",
              duration: "26min",
              videoUrl: "https://ia904600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/06.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "07.Episodio 7",
              duration: "29min",
              videoUrl: "https://ia804600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/07.Terminator%20Zero.mp4",
            },
            {
              number: 1,
              title: "08.Episodio 8",
              duration: "29min",
              videoUrl: "https://ia804600.us.archive.org/11/items/03.-terminator-zero-anim3/Terminator%20Zero/08.Terminator%20Zero.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Caballeros del zodiaco - La leyenda del santuario",
      description: "Después de que Seiya la salva de un ataque asesino, Saori Kido, una niña con misteriosos poderes, descubre su destino y decide unirse a Seiya y el resto de los caballeros y acompañarlos en su misión.",
      type:"Pelicula, Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/KOTZLCZ-1.jpg",
      genre: ["Acción", "Artes marciales", "Fantástica", "Aventura​", "Ciencia ficción"],
      age: "12",
      duration: "1h 33min",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Caballeros%20del%20Zodiaco%20_La%20Leyenda%20del%20Santuario_%20Trailer%20Oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "Caballeros del Zodiaco - La leyenda del santuario",
              duration: "1h 12min",
              videoUrl: "https://ia804601.us.archive.org/31/items/KOTZGDSANTP/Caballeros%20del%20zodiaco%20-%20Los%20guerreros%20del%20santuario.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Darling in the Franxx",
      description: "En un futuro distante la humanidad ha creado Plantation, una ciudad fortaleza móvil construida sobre las ruinas del mundo y en la que ha florecido la civilización. En la ciudad hay barracones especiales para pilotos llamados Mistilteinn, aunque popularmente se los conoce como (jaulas de pájaros). Allí es donde viven estos chicos... sin saber nada del mundo exterior, sin poder sentir nunca el enorme cielo. Su única misión en la vida siempre fue luchar.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/DarlingInFXX-1.jpg",
      genre: ["Acción", "Ciencia ficción", "Drama", "Romance​​​"],
      age: "15",
      duration: "24 Episodios",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Darling%20in%20the%20FranXX%20_%20TRAILER%20OFICIAL.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Sola y solitario",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/01.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "02.Lo que siginifica conectarse",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/02.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "03.Títere de combate",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/03.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "04.Flap flap",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/04.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "05.Tu espina, mi insignia",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/05.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "06.Darling in the FRANXX",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/06.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "07.Moratoria de estrellas fugaces",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/07.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "08.Chicos x Chicas",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/08.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "09.Bomba triangular",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/09.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "10.La ciudad de la eternidad",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/10.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "11.Cambio de compañeros",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/11.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "12.El jardín donde todo empezó",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/12.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "13.La bestia y el príncipe",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/13.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "14.Castigo y confesión",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/14.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "15.Jian",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/15.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "16.Los días de nuestras vidas",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/16.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "17.Edén",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/17.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "18.Cuando florecen los cerezos",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/18.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "19.Inhumanidad",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/19.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "20.Un nuevo mundo",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/20.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "21.Por ti, mi amor",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/21.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "22.Pioneros",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/22.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "23.Darling in the FRANXX",
              duration: "24min",
              videoUrl: "https://ia800807.us.archive.org/19/items/darling1nth3fr4n/23.DarlingInTheFranXX.mp4",
            },
            {
              number: 1,
              title: "24.Nunca me dejes ir",
              duration: "24min",
              videoUrl: "https://ia600807.us.archive.org/19/items/darling1nth3fr4n/24.DarlingInTheFranXX.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
      description: "Obligado por su hermana menor a jugar a un otome para que pueda ver el final a cambio de no acusarlo ante sus padres de cierto asunto, Leon juega hasta la extenuación pese al odio que siente por el juego, su mundo y sus personajes. Cuando muere repentinamente y despierta... ¡es un personaje de fondo en el mundo del otome que tanto odia!",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/otomegame-1.jpg",
      genre: ["Ciencia ficción", "fantástica", "comedia", "isekai", "harem", "romance​"],
      age: "14",
      duration: "12 Episodios",
      trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/Otome%20game%20-%20Trailer%20oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Odio este mundo",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Oye, chica, ¿vamos a beber té?",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.Te reto a un duelo príncipe",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.¿Le molesta si me contengo?",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.Es lo máximo",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.Es mi primer festival escolar",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Odiamos al mismo chico guapo",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.No estoy jugando",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.Una chica muy conveniente",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.A diferencia de los falsos nobles",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.Lo que puedo hacer ahora",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.Por muy cruel que sea el mundo de este juego otome",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/16/items/Otomegamesekaiwmksekaudesu/Ep12.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Castlevania",
      description: "Los últimos sobrevivientes de un clan caído en desgracia luchan por salvar Europa del Este de Drácula. Inspirado en la serie clásica de videojuegos.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/CastleV4n1a-1.jpeg",
      genre: ["	Animación", "Horror", "Fantasía", "Acción", "Aventura"],
      age: "18",
      duration: "4 Temporadas",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Castlevania_%20Official%20Trailer.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Botella de bruja",
              duration: "25min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.1/01.Castlevania%20T1.mp4",
            },
            {
              number: 1,
              title: "02.Necrópolis",
              duration: "23min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.1/02.Castlevania%20T1.mp4",
            },
            {
              number: 1,
              title: "03.Laberinto",
              duration: "24min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.1/03.Castlevania%20T1.mp4",
            },
          ],
        },
        {
          number: 2,
          episodes: [
            {
              number: 2,
              title: "01.Consejo de guerra",
              duration: "25min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/01.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "02.Hogares ancestrales",
              duration: "25min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/02.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "03.Batallas ocultas",
              duration: "27min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/03.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "04.Mástil roto",
              duration: "25min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/04.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "05.Último hechizo",
              duration: "24min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/05.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "06.El río",
              duration: "25min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/06.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "07.Por amor",
              duration: "28min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/07.Castlevania%20T2.mp4",
            },
            {
              number: 2,
              title: "08.El fin de los dias",
              duration: "29min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.2/08.Castlevania%20T2.mp4",
            },
          ],
        },
        {
          number: 3,
          episodes: [
            {
              number: 3,
              title: "01.Muertos de buen corazón",
              duration: "28min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/01.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "02.La reparación de mi corazón",
              duration: "30min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/02.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "03.Investigadores",
              duration: "28min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/03.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "04.Tengo un plan",
              duration: "31min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/04.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "05.Sede de civilización y refinamiento",
              duration: "22min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/05.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "06.El buen sueño",
              duration: "24min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/06.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "07.Cosas peores que la traición",
              duration: "25min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/07.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "08.Qué depara la noche",
              duration: "25min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/08.Castlevania%20T3.mp4",
            },
            {
              number: 3,
              title: "09.La cosecha",
              duration: "25min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.3/09.Castlevania%20T3.mp4",
            },
          ],
        },
        {
          number: 4,
          episodes: [
            {
              number: 4,
              title: "01.La muerte lo activa",
              duration: "24min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/01.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "02.Tener el mundo",
              duration: "23min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/02.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "03.Sigue caminando",
              duration: "29min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/03.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "04.Sacrificar todo",
              duration: "28min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/04.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "05.Volver a la vida",
              duration: "25min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/05.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "06.No merecen mi sangre",
              duration: "31min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/06.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "07.La gran obra",
              duration: "26min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/07.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "08.Magia de muerte",
              duration: "24min",
              videoUrl: "https://ia904601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/08.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "09.El final",
              duration: "31min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/09.Castlevania%20T4.mp4",
            },
            {
              number: 4,
              title: "10.Ha sido un viaje extraño",
              duration: "27min",
              videoUrl: "https://ia804601.us.archive.org/4/items/c4stl3v4ni4T1T2T3T4/Castlev4n1a/Temp.4/10.Castlevania%20T4.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Invasión en las alturas",
      description: "La joven Yuri se encuentra en la cima de un rascacielos en un mundo extraño, donde debe sobrevivir los embates de atacantes enmascarados que buscan matar a sus presas.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/HRInvasion-1.jpg",
      genre: ["Supervivencia", "misterio", "acción", "drama"],
      age: "16",
      duration: "12 Episodios",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Invasi%C3%B3n%20en%20las%20alturas%20_%20Tr%C3%A1iler.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.No entiendo este mundo",
              duration: "25min",
              videoUrl: "https://ia600809.us.archive.org/21/items/Invaenlasalt1/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Tengo un nuevo propósito",
              duration: "25min",
              videoUrl: "https://ia600809.us.archive.org/21/items/Invaenlasalt1/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.Lo siento, Mayuko Nise",
              duration: "25min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.No me dejaré vencer por este mundo",
              duration: "25min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.Esa es un arma increible",
              duration: "26min",
              videoUrl: "https://ia600809.us.archive.org/21/items/Invaenlasalt1/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.Si me convirtiera en una diosa perfecta",
              duration: "25min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Acabaré con este reino",
              duration: "25min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.He perdido mi humanidad, pero está bien",
              duration: "26min",
              videoUrl: "https://ia600809.us.archive.org/21/items/Invaenlasalt1/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.¿Quien de nosotros tendrá una vida genial?",
              duration: "26min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Nuestro enemigo es todo aquel que desea el caos",
              duration: "26min",
              videoUrl: "https://ia600809.us.archive.org/21/items/Invaenlasalt1/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.¡Yo soy la justicia!",
              duration: "25min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.Está es una invasión en las alturas",
              duration: "27min",
              videoUrl: "https://ia800809.us.archive.org/21/items/Invaenlasalt1/Ep12.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "The Yakuza's Guide to Babysitting",
      description: "Kirishima es un joven y violento yakuza al que su patriarca le impone la tarea de cuidar de su hija, de tan solo 7 años de edad.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/kimichoumito-1.jpg",
      genre: ["Comedia", "Recuentos de la vida"],
      age: "14",
      duration: "12 Episodios",
      trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/Kumicho%20Musume%20to%20Sewagakari%20-%20Trailer%20oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.La guía de crianza del yakuza",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Una persona amable",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.Una visita y una reunión",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.¿Y si empezamos a transmitir?",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/7/items/KimichoMusume/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.El dia libre de Kirishima",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.La primera amistad",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/7/items/KimichoMusume/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.El objetivo definitivo",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.Cuantó tiempo",
              duration: "23min",
              videoUrl: "https://ia600607.us.archive.org/7/items/KimichoMusume/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.El plan Kirishima",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Una mala persona",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.Fuegos artificales y promesas",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.El cuidador de la señorita",
              duration: "23min",
              videoUrl: "https://ia800607.us.archive.org/7/items/KimichoMusume/Ep12.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Komi San Cant communicate",
      description: "En una escuela llena de personalidades únicas, Tadano ayuda a la tímida e introvertida Komi a alcanzar su meta personal: hacerse amiga de 100 personas.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Komi-1.jpg",
      genre: ["Romántico", "Comedia", "Slice of life"],
      age: "12",
      duration: "24 Episodios",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/Komi%20Can_t%20Communicate%20_%20Trailer%20oficial.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Es solo que quisiera poder hablar",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Es solo un amigo de la infancia. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.Es solo pánico escénico.Y algo más",
              duration: "25min",
              videoUrl: "https://ia600406.us.archive.org/25/items/Komisanwat1/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.Es solo un exámen físico. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.Es solo mi uniforme de verano. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.Es solo una broma. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Es solo una piscina. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.Es solo Obon. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600406.us.archive.org/25/items/Komisanwat1/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.Es solo un niño de campo. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Es solo el dia del deporte. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.Es solo una propuesta para el festival cultural. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600406.us.archive.org/25/items/Komisanwat1/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.Es solo el festival cultural. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800406.us.archive.org/25/items/Komisanwat1/Ep12.mp4",
            },
            {
              number: 1,
              title: "13.Es solo la llegada del invierno. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800108.us.archive.org/21/items/Komisant2/Ep1.mp4",
            },
            {
              number: 1,
              title: "14.Es solo un tifon. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800108.us.archive.org/21/items/Komisant2/Ep2.mp4",
            },
            {
              number: 1,
              title: "15.Es solo un sentimiento. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600108.us.archive.org/21/items/Komisant2/Ep3.mp4",
            },
            {
              number: 1,
              title: "16.Es solo una feliz navidad",
              duration: "25min",
              videoUrl: "https://ia800108.us.archive.org/21/items/Komisant2/Ep4.mp4",
            },
            {
              number: 1,
              title: "17.Es solo un muñeco de nieve. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600108.us.archive.org/21/items/Komisant2/Ep5.mp4",
            },
            {
              number: 1,
              title: "18.Es solo el nuevo año de todos. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600108.us.archive.org/21/items/Komisant2/Ep6.mp4",
            },
            {
              number: 1,
              title: "19.Es solo un malentendido. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800108.us.archive.org/21/items/Komisant2/Ep7.mp4",
            },
            {
              number: 1,
              title: "20.Es solo una excursión. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600108.us.archive.org/21/items/Komisant2/Ep8.mp4",
            },
            {
              number: 1,
              title: "21.Es solo el segundo dia de la excursión. Y algo más",
              duration: "25min",
              videoUrl: "https://ia600108.us.archive.org/21/items/Komisant2/Ep9.mp4",
            },
            {
              number: 1,
              title: "22.Es solo el dia de san valentín",
              duration: "25min",
              videoUrl: "https://ia600108.us.archive.org/21/items/Komisant2/Ep10.mp4",
            },
            {
              number: 1,
              title: "23.Son solo unas mallas rotas. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800108.us.archive.org/21/items/Komisant2/Ep11.mp4",
            },
            {
              number: 1,
              title: "24.Es solo el día blanco. Y algo más",
              duration: "25min",
              videoUrl: "https://ia800108.us.archive.org/21/items/Komisant2/Ep12.mp4",
            },
          ],
        },
      ],
    },
    {
      title: "Wind Breaker",
      description: "El lugar donde las calificaciones medias son las peores, pero las peleas son las mejores. La Preparatoria Furin es bien conocida por ser una preparatoria repleta de delincuentes. Haruka Sakura, estudiante de primer año, llega como novato con ganas de abrirse paso luchando hasta lo más alto. Sin embargo, la Preparatoria Furin tiene ahora un grupo que protege las calles de la ciudad con el nombre de “Wind Breaker”. ¡Este es el inicio de la leyenda de Sakura, el delincuente de preparatoria!",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/Windbreaker-1.jpg",
      genre: ["Acción", "Drama"],
      age: "14",
      duration: "13 Episodios",
      trailerVideo: "https://ia800609.us.archive.org/14/items/Trailerspelisserieanimes/WIND%20BREAKER%20_%20MAIN%20TRAILER.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Sakura y la furin",
              duration: "23min",
              videoUrl: "https://ia902209.us.archive.org/3/items/Breakerwind/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Los héroes idolatrados",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.El hombre en la cima",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.Enfrentamiento",
              duration: "23min",
              videoUrl: "https://ia902209.us.archive.org/3/items/Breakerwind/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.Un buen hombre",
              duration: "23min",
              videoUrl: "https://ia902209.us.archive.org/3/items/Breakerwind/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.Persiguiendo esa espalda",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Una pelea que no puedo perder",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.Heredando sentimientos",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.El método de Umemiya",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Diálogo",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.Nuevos amigos",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.Alguien de confianza",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep12.mp4",
            },
            {
              number: 1,
              title: "13.Por un amigo",
              duration: "23min",
              videoUrl: "https://ia802209.us.archive.org/3/items/Breakerwind/Ep13.mp4",
            },
          ],
        },
      ],
    },
    {      
      title: "Rurouni Kenshin",
      description: "Kenshin es un vagabundo que recorre Tokio y conoce por accidente a Kaoru, una joven que busca a Hitokiri Battosai.",
      type:"Anime",
      thumbnailUrl:
        "https://raw.githubusercontent.com/Hugoxter-twilght14/images-for-playMovies/refs/heads/main/anime-images/ruronoi-1.jpg",
      genre: ["Acción", "aventura", "artes marciales", "comedia", "drama", "romance​"],
      age: "14",
      duration: "24 Episodios",
      trailerVideo: "https://ia600609.us.archive.org/14/items/Trailerspelisserieanimes/Rurouni%20Kenshin%20%20_%20Trailer.mp4",
      seasons: [
        {
          number: 1,
          episodes: [
            {
              number: 1,
              title: "01.Kenshin es Battosai Himura",
              duration: "23min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep1.mp4",
            },
            {
              number: 1,
              title: "02.Yahiko Miojin, Samurái de la prefectura de Tokio",
              duration: "23min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep2.mp4",
            },
            {
              number: 1,
              title: "03.La escuela Kamiya Kasshin reinicia operaciones",
              duration: "23min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep3.mp4",
            },
            {
              number: 1,
              title: "04.Sanosuke Sagara, el hombre de las peleas",
              duration: "23min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep4.mp4",
            },
            {
              number: 1,
              title: "05.Se nos une un nuevo amigo",
              duration: "23min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep5.mp4",
            },
            {
              number: 1,
              title: "06.El sombrero negro",
              duration: "23min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep6.mp4",
            },
            {
              number: 1,
              title: "07.Dos Hitokiris",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep7.mp4",
            },
            {
              number: 1,
              title: "08.La hermosa fugitiva",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep8.mp4",
            },
            {
              number: 1,
              title: "09.El ataque de los oniwaban",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep9.mp4",
            },
            {
              number: 1,
              title: "10.Un motivo para actuar",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep10.mp4",
            },
            {
              number: 1,
              title: "11.La valentía de Hannya y las cicatrices de Shikijo",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep11.mp4",
            },
            {
              number: 1,
              title: "12.El capitan Aoshi Shinomori",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep12.mp4",
            },
            {
              number: 1,
              title: "13.Después del duelo a muerte",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep13.mp4",
            },
            {
              number: 1,
              title: "14.La lucha de Yahiko",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep14.mp4",
            },
            {
              number: 1,
              title: "15.Ese hombre se llama Raijuta",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep15.mp4",
            },
            {
              number: 1,
              title: "16.El hombre ideal",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep16.mp4",
            },
            {
              number: 1,
              title: "17.La conclusión del duelo",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep17.mp4",
            },
            {
              number: 1,
              title: "18.Sanosuke y el nishiki-e",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep18.mp4",
            },
            {
              number: 1,
              title: "19.Tsunan y el nishiki-e",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep19.mp4",
            },
            {
              number: 1,
              title: "20.Epopeya de un espadachín de la era Meiji, acto cero Pt.1",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep20.mp4",
            },
            {
              number: 1,
              title: "21.Epopeya de un espadachín de la era Meiji, acto cero Pt.2",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep21.mp4",
            },
            {
              number: 1,
              title: "22.Renace el lobo",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep22.mp4",
            },
            {
              number: 1,
              title: "23.El lobo muestra sus colmillos",
              duration: "22min",
              videoUrl: "https://ia800805.us.archive.org/34/items/S4mur41X/Ep23.mp4",
            },
            {
              number: 1,
              title: "24.14 de Mayo del año 11 de la era Meiji",
              duration: "22min",
              videoUrl: "https://ia600805.us.archive.org/34/items/S4mur41X/Ep24.mp4",
            },
          ],
        },
      ],
    },
  ];
  